// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEmMY4opZ2Lz9PUq4OSTz2uRiOkVyl03c',
    appId: '1:788182269102:web:d658c10563131e8bc1813f',
    messagingSenderId: '788182269102',
    projectId: 'aplikasi-uang-kas-920ca',
    authDomain: 'aplikasi-uang-kas-920ca.firebaseapp.com',
    storageBucket: 'aplikasi-uang-kas-920ca.appspot.com',
    measurementId: 'G-KQ2N1E9RW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1HiBBIpisOz65bkDPEWEMRDdeONobJw',
    appId: '1:788182269102:android:3de2200eb0628f65c1813f',
    messagingSenderId: '788182269102',
    projectId: 'aplikasi-uang-kas-920ca',
    storageBucket: 'aplikasi-uang-kas-920ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmxKrIBcBibMdtpC2MwoVsFNCKlGo8-nM',
    appId: '1:788182269102:ios:b7a6fe2c7d495957c1813f',
    messagingSenderId: '788182269102',
    projectId: 'aplikasi-uang-kas-920ca',
    storageBucket: 'aplikasi-uang-kas-920ca.appspot.com',
    iosBundleId: 'com.example.cashstory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmxKrIBcBibMdtpC2MwoVsFNCKlGo8-nM',
    appId: '1:788182269102:ios:ba8778686cd546d8c1813f',
    messagingSenderId: '788182269102',
    projectId: 'aplikasi-uang-kas-920ca',
    storageBucket: 'aplikasi-uang-kas-920ca.appspot.com',
    iosBundleId: 'com.example.cashstory.RunnerTests',
  );
}
